spring:
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
  security:
    user:
      name: ${USER_NAME:username}
      password: ${USER_PASSWORD:password}
  liquibase:
    enabled: true
    change-log: classpath:/db/changelog/master.xml
  ai:
    openai:
      api-key: ${OPENAI_API_KEY}
      base-url: ${OPENAI_BASE_URL}
      chat:
        options:
          model: ${OPENAI_MODEL}
        completions-path: /api/v3/chat/completions
logging:
  level:
    org.springframework.security: TRACE